### ISSUE TITLE
Congratulations!

### ISSUE THREAD

**Issue by ccauet** [MaxNoe/phd_thesis#1]
I'm impressed by how easily reproducible this seems; sadly I have no access to the data :(

Would you mind providing the final (sic!) `phd_mnoethe.pdf` or a link pointing to it?

**Comment by maxnoe** [comment]
Thx, Christophe!

The pdf is published via eldorado here: http://dx.doi.org/10.17877/DE290R-21143

I have added it to the fron page of the repo
